name: very_good_rx_blog_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  auto_route: ^5.0.4
  cached_network_image: ^3.2.3
  dart_either: ^1.0.0
  dartx: ^1.1.0
  disposebag: ^1.5.1
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  lazy_load_indexed_stack: ^0.1.4
  logger: ^1.1.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  rxdart_ext: ^0.2.7
  shimmer: ^2.0.0
  timeago: ^3.3.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.3.0
  chopper_generator: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

flutter_gen:
  output: lib/common/gen/

  integrations:
    flutter_svg: true
