name: very_good_rx_blog_app
description: My Very Good Rx Blog App
version: 1.0.0+1
repository: https://github.com/dungngminh/very_good_blog_app
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cached_network_image: ^3.2.1
  chopper: ^6.0.0
  connectivity_plus: ^2.3.6+1
  dart_either: ^1.0.0
  disposebag: ^1.5.1
  draggable_home:
    git:
      url: https://github.com/dungngminh/draggable_home
      ref: ec8c4b6
  easy_debounce: ^2.0.2+1
  equatable: ^2.0.5
  firebase_core: ^1.21.1
  firebase_storage: ^10.3.7

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^5.4.1
  flutter_secure_storage: ^6.1.0
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.4
  fluttertoast: ^8.0.9
  formz: ^0.4.1
  get_it: ^7.2.0
  go_router: ^4.2.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  lazy_load_indexed_stack: ^0.1.4
  path_provider: ^2.0.11
  phosphor_flutter: ^1.4.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  rxdart_ext: ^0.2.7
  shimmer: ^2.0.0
  timeago_flutter: ^1.2.0


dev_dependencies:
  auto_route_generator: ^5.0.2
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  chopper_generator: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

flutter_gen:
  output: lib/app/config/gen/

  integrations:
    flutter_svg: true
