version: '3.4'

services:
  database:
    image: mongo
    restart: always
    env_file:
      - ./db.env
    volumes:
      - db-mong:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=db-mongo
    networks:
      - docker_network

  djongo:
    restart: always
    image: djongo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"
    environment:
      DEBUG: 'true'
    stdin_open: true
    tty: true
    depends_on:
      - database
    networks:
      - docker_network
  
volumes:
  db-mong:

networks:
  docker_network:
    driver: bridge